/* Simulation code for nb_hydr_static_v6 generated by the OpenModelica Compiler OpenModelica v1.22.3 (64-bit). */
#if !defined(nb_hydr_static_v6__MODEL_H)
#define nb_hydr_static_v6__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "nb_hydr_static_v6_functions.h"

#define _omcQ_24DER_24Buildings_24PFluid_24PMovers_24PBaseClasses_24PCharacteristics_24Ppressure_index 0
#define _omcQ_24DER_24Buildings_24PUtilities_24PMath_24PFunctions_24PcubicHermiteLinearExtrapolation_index 1
#define _omcQ_24DER_24Modelica_24PFluid_24PUtilities_24PcubicHermite_index 2
#define Buildings_Fluid_BaseClasses_FlowModels_basicFlowFunction__m__flow_index 3
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_index 4
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_power_index 5
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters_index 6
#define Buildings_Fluid_Movers_BaseClasses_Characteristics_pressure_index 7
#define Buildings_Utilities_Math_Functions_cubicHermiteLinearExtrapolation_index 8
#define Buildings_Utilities_Math_Functions_isMonotonic_index 9
#define Buildings_Utilities_Math_Functions_regStep_index 10
#define Buildings_Utilities_Math_Functions_smoothMax_index 11
#define Buildings_Utilities_Math_Functions_splineDerivatives_index 12
#define Buildings_Utilities_Math_Functions_BaseClasses_smoothTransition_index 13
#define Modelica_Blocks_Continuous_Internal_Filter_Utilities_toHighestPowerOne_index 14
#define Modelica_Blocks_Continuous_Internal_Filter_base_CriticalDamping_index 15
#define Modelica_Blocks_Continuous_Internal_Filter_coefficients_lowPass_index 16
#define Modelica_Blocks_Continuous_Internal_Filter_roots_lowPass_index 17
#define Modelica_Fluid_Utilities_checkBoundary_index 18
#define Modelica_Fluid_Utilities_cubicHermite_index 19
#define Modelica_Fluid_Utilities_evaluatePoly3__derivativeAtZero_index 20
#define Modelica_Fluid_Utilities_regRoot_index 21
#define Modelica_Fluid_Utilities_regRoot2_index 22
#define Modelica_Fluid_Utilities_regStep_index 23
#define Modelica_Fluid_Utilities_regRoot2_regRoot2__utility_index 24
#define Modelica_Utilities_Streams_error_index 25
#define nb__hydr__static__v6_checkvalve__1_valveCharacteristic_index 26
#define nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState_index 27
#define nb__hydr__static__v6_checkvalve__1_Medium_density_index 28
#define nb__hydr__static__v6_checkvalve__1_Medium_setState__phX_index 29
#define nb__hydr__static__v6_checkvalve__1_Medium_temperature_index 30
#define nb__hydr__static__v6_checkvalve__2_valveCharacteristic_index 31
#define nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState_index 32
#define nb__hydr__static__v6_checkvalve__2_Medium_density_index 33
#define nb__hydr__static__v6_checkvalve__2_Medium_setState__phX_index 34
#define nb__hydr__static__v6_checkvalve__2_Medium_temperature_index 35
#define nb__hydr__static__v6_checkvalve__3_valveCharacteristic_index 36
#define nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState_index 37
#define nb__hydr__static__v6_checkvalve__3_Medium_density_index 38
#define nb__hydr__static__v6_checkvalve__3_Medium_setState__phX_index 39
#define nb__hydr__static__v6_checkvalve__3_Medium_temperature_index 40
#define nb__hydr__static__v6_checkvalve__4_valveCharacteristic_index 41
#define nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState_index 42
#define nb__hydr__static__v6_checkvalve__4_Medium_density_index 43
#define nb__hydr__static__v6_checkvalve__4_Medium_setState__phX_index 44
#define nb__hydr__static__v6_checkvalve__4_Medium_temperature_index 45
#define nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState_index 46
#define nb__hydr__static__v6_chiller__1_Medium_dynamicViscosity_index 47
#define nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState_index 48
#define nb__hydr__static__v6_chiller__2_Medium_dynamicViscosity_index 49
#define nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState_index 50
#define nb__hydr__static__v6_chiller__3_Medium_dynamicViscosity_index 51
#define nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState_index 52
#define nb__hydr__static__v6_chiller__4_Medium_dynamicViscosity_index 53
#define nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState_index 54
#define nb__hydr__static__v6_chw__ret_Medium_setState__pTX_index 55
#define nb__hydr__static__v6_chw__ret_Medium_specificEnthalpy_index 56
#define nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState_index 57
#define nb__hydr__static__v6_chw__sup_Medium_setState__pTX_index 58
#define nb__hydr__static__v6_chw__sup_Medium_specificEnthalpy_index 59
#define nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState_index 60
#define nb__hydr__static__v6_chwp__1_Medium_specificEnthalpy_index 61
#define nb__hydr__static__v6_chwp__1_eff_getArrayAsString_index 62
#define nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState_index 63
#define nb__hydr__static__v6_chwp__1_preSou_Medium_density_index 64
#define nb__hydr__static__v6_chwp__1_preSou_Medium_setState__phX_index 65
#define nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState_index 66
#define nb__hydr__static__v6_chwp__1_vol_Medium_density_index 67
#define nb__hydr__static__v6_chwp__1_vol_Medium_specificEnthalpy__pTX_index 68
#define nb__hydr__static__v6_chwp__1_vol_Medium_temperature__phX_index 69
#define nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState_index 70
#define nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState_index 71
#define nb__hydr__static__v6_chwp__2_Medium_specificEnthalpy_index 72
#define nb__hydr__static__v6_chwp__2_eff_getArrayAsString_index 73
#define nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState_index 74
#define nb__hydr__static__v6_chwp__2_preSou_Medium_density_index 75
#define nb__hydr__static__v6_chwp__2_preSou_Medium_setState__phX_index 76
#define nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState_index 77
#define nb__hydr__static__v6_chwp__2_vol_Medium_density_index 78
#define nb__hydr__static__v6_chwp__2_vol_Medium_specificEnthalpy__pTX_index 79
#define nb__hydr__static__v6_chwp__2_vol_Medium_temperature__phX_index 80
#define nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState_index 81
#define nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState_index 82
#define nb__hydr__static__v6_chwp__3_Medium_specificEnthalpy_index 83
#define nb__hydr__static__v6_chwp__3_eff_getArrayAsString_index 84
#define nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState_index 85
#define nb__hydr__static__v6_chwp__3_preSou_Medium_density_index 86
#define nb__hydr__static__v6_chwp__3_preSou_Medium_setState__phX_index 87
#define nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState_index 88
#define nb__hydr__static__v6_chwp__3_vol_Medium_density_index 89
#define nb__hydr__static__v6_chwp__3_vol_Medium_specificEnthalpy__pTX_index 90
#define nb__hydr__static__v6_chwp__3_vol_Medium_temperature__phX_index 91
#define nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState_index 92
#define nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState_index 93
#define nb__hydr__static__v6_chwp__4_Medium_specificEnthalpy_index 94
#define nb__hydr__static__v6_chwp__4_eff_getArrayAsString_index 95
#define nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState_index 96
#define nb__hydr__static__v6_chwp__4_preSou_Medium_density_index 97
#define nb__hydr__static__v6_chwp__4_preSou_Medium_setState__phX_index 98
#define nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState_index 99
#define nb__hydr__static__v6_chwp__4_vol_Medium_density_index 100
#define nb__hydr__static__v6_chwp__4_vol_Medium_specificEnthalpy__pTX_index 101
#define nb__hydr__static__v6_chwp__4_vol_Medium_temperature__phX_index 102
#define nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState_index 103
#define nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState_index 104
#define nb__hydr__static__v6_terminal__resist_Medium_dynamicViscosity_index 105

extern void nb_hydr_static_v6_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void nb_hydr_static_v6_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void nb_hydr_static_v6_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void nb_hydr_static_v6_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int nb_hydr_static_v6_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_checkForAsserts(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int nb_hydr_static_v6_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* nb_hydr_static_v6_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* nb_hydr_static_v6_relationDescription(int i);
extern void nb_hydr_static_v6_function_initSample(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int nb_hydr_static_v6_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int nb_hydr_static_v6_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int nb_hydr_static_v6_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int nb_hydr_static_v6_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int nb_hydr_static_v6_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int nb_hydr_static_v6_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int nb_hydr_static_v6_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int nb_hydr_static_v6_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int nb_hydr_static_v6_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int nb_hydr_static_v6_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int nb_hydr_static_v6_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int nb_hydr_static_v6_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int nb_hydr_static_v6_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* nb_hydr_static_v6_linear_model_frame(void);
extern const char* nb_hydr_static_v6_linear_model_datarecovery_frame(void);
extern int nb_hydr_static_v6_mayer(DATA* data, modelica_real** res, short *);
extern int nb_hydr_static_v6_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int nb_hydr_static_v6_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int nb_hydr_static_v6_setInputData(DATA *data, const modelica_boolean file);
extern int nb_hydr_static_v6_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void nb_hydr_static_v6_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void nb_hydr_static_v6_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int nb_hydr_static_v6_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void nb_hydr_static_v6_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void nb_hydr_static_v6_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int nb_hydr_static_v6_inputNames(DATA* data, char ** names);
extern int nb_hydr_static_v6_dataReconciliationInputNames(DATA* data, char ** names);
extern int nb_hydr_static_v6_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int nb_hydr_static_v6_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int nb_hydr_static_v6_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int nb_hydr_static_v6_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "nb_hydr_static_v6_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(nb_hydr_static_v6__MODEL_H) */


