/* Additional record code for nb_hydr_static_v6 generated by the OpenModelica Compiler OpenModelica v1.22.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "nb_hydr_static_v6_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc_added 1
const char* Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc__fields[3] = {"n","V_flow","dp"};
struct record_description Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc = {
  "Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal", /* package_record__X */
  "Buildings.Fluid.Movers.BaseClasses.Characteristics.flowParametersInternal", /* package.record_X */
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal__desc__fields
};

void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* ths = (Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_ths);
  // ths->_n has no default value.
  alloc_real_array(&(ths->_V_flow), 1, (_index_t)ths->_n); // ths->_V_flow has no default value.
  alloc_real_array(&(ths->_dp), 1, (_index_t)ths->_n); // ths->_dp has no default value.
}
void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_integer in_n, real_array in_V_flow, real_array in_dp) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* dst = (Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_dst);
  dst->_n = in_n;
  dst->_V_flow = in_V_flow;
  dst->_dp = in_dp;
}

void Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* src = (Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_src);
  Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal* dst = (Buildings_Fluid_Movers_BaseClasses_Characteristics_flowParametersInternal*)(v_dst);
  dst->_n = src->_n;
  real_array_copy_data(src->_V_flow, dst->_V_flow);
  real_array_copy_data(src->_dp, dst->_dp);
}


#define Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters__desc_added 1
const char* Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters__desc__fields[2] = {"V_flow","P"};
struct record_description Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters__desc = {
  "Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters", /* package_record__X */
  "Buildings.Fluid.Movers.BaseClasses.Characteristics.powerParameters", /* package.record_X */
  Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters__desc__fields
};

void Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters_construct_p(threadData_t *threadData, void* v_ths ) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters* ths = (Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters*)(v_ths);
  modelica_integer tmp6;
  generic_array_create_flexible(&ths->_V_flow, 1); // ths->_V_flow has unknown size and no default value. It is flexible.
  tmp6 = size_of_dimension_base_array(ths->_V_flow, ((modelica_integer) 1));
  alloc_real_array(&(ths->_P), 1, (_index_t)tmp6); // ths->_P has no default value.
}
void Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters_wrap_vars_p(threadData_t *threadData, void* v_dst , real_array in_V_flow, real_array in_P) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters* dst = (Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters*)(v_dst);
  dst->_V_flow = in_V_flow;
  dst->_P = in_P;
}

void Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters_copy_p(void* v_src, void* v_dst) {
  Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters* src = (Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters*)(v_src);
  Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters* dst = (Buildings_Fluid_Movers_BaseClasses_Characteristics_powerParameters*)(v_dst);
  real_array_copy_data(src->_V_flow, dst->_V_flow);
  real_array_copy_data(src->_P, dst->_P);
}


#define nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.checkvalve_1.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState* src = (nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_checkvalve__1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.checkvalve_2.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState* src = (nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_checkvalve__2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.checkvalve_3.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState* src = (nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_checkvalve__3_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.checkvalve_4.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState* src = (nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_checkvalve__4_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chiller_1.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chiller__1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chiller_2.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chiller__2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chiller_3.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chiller__3_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chiller_4.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chiller__4_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chw_ret.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chw__ret_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chw_sup.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chw__sup_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_1.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_1.preSou.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__1_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_1.vol.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__1_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_1.vol.steBal.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__1_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_2.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__2_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_2.preSou.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__2_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_2.vol.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__2_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_2.vol.steBal.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__2_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_3.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__3_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_3.preSou.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__3_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_3.vol.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__3_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_3.vol.steBal.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__3_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_4.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__4_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_4.preSou.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__4_preSou_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_4.vol.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__4_vol_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.chwp_4.vol.steBal.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState* src = (nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_chwp__4_vol_steBal_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState__desc_added 1
const char* nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState__desc = {
  "nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState", /* package_record__X */
  "nb_hydr_static_v6.terminal_resist.Medium.ThermodynamicState", /* package.record_X */
  nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState__desc__fields
};

void nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState* ths = (nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState* src = (nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState*)(v_src);
  nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState* dst = (nb__hydr__static__v6_terminal__resist_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}

#ifdef __cplusplus
}
#endif

